// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv5s76J3-TTK3of2Ot00VubX5oiEJ5KCo',
    appId: '1:423049874678:android:7f06b27628fd84992970d7',
    messagingSenderId: '423049874678',
    projectId: 'fisheryapp-914e8',
    storageBucket: 'fisheryapp-914e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBacaoNA_sby-MmAAiVg_J9oL-iRGmiQXg',
    appId: '1:423049874678:ios:7ef6456765d612e52970d7',
    messagingSenderId: '423049874678',
    projectId: 'fisheryapp-914e8',
    storageBucket: 'fisheryapp-914e8.appspot.com',
    androidClientId: '423049874678-tucmljjm4aga08am2u0ec33mjq903018.apps.googleusercontent.com',
    iosClientId: '423049874678-u3e1gafl12rkv4caej85pjm52sjcr3du.apps.googleusercontent.com',
    iosBundleId: 'dev.broseph.fishApp',
  );
}
